### ISSUE TITLE
New Play services 

### ISSUE THREAD

**Issue by Happyfeet01** [micro5k/microg-unofficial-installer#12]
Hello,

I get every an update Notification for the play Services. What can I do? It's installed from microg.

**Comment by ale5000-git** [comment]
microG GmsCore to work correctly need to spoof itself as Google Play Services.
So if an app ask to update Google Play Services, it is asking to update microG GmsCore.

My installer already install the latest version on Android 5 and higher.

If you have a less recent version of Android to workaround a bug in microG GmsCore you have to follow this procedure:
- Flash the installer
- Add a Google account
- Then update microG GmsCore (as normal app) from F-Droid or from [here](https://microg.org/download.html) (use the drop-down menu to select the latest version).

**Comment by theScrabi** [comment]
> wontfix

I still think this should be removed.

**Comment by ale5000-git** [comment]
@Happyfeet01: I have released a new version, it should fix the update notification.
