### ISSUE TITLE
How could I uninstall it?

### ISSUE THREAD

**Issue by ghost** [micro5k/microg-unofficial-installer#14]
I have Android 9 and was trying to use yours script.
Unfortunately unifiednlp do not have location to test geocoder and I can't force it to do so.
Do you have some kind of uninstall zip, or should I remove every app manualy?

**Comment by ale5000-git** [comment]
Currently you have to extract the file "uninstall.sh" from the zip and execute it manually as root.

In the future I plan to simplify it.
Also I want to fix your problems with Android 9.
I will hopefully release a new version this week (if I find enough free time).

**Comment by ale5000-git** [comment]
@smigima: Hi, could you please test microG unofficial installer 1.0.32 beta?

**Comment by puffnfresh** [comment]
I ran something like this:

```
$ adb shell
$$ mkdir /sdcard/Download/microG
$$ cd /sdcard/Download/microG
$$ unzip ../microg*.zip
# su
# mount -o rw,remount /system
# sh uninstall.sh 
```

Looks like it worked!
