### ISSUE TITLE
Support OTA zip installation in A/B (Seamless) devices

### ISSUE THREAD

**Issue by ale5000-git** [micro5k/microg-unofficial-installer#17]
ToDO: Test OTA zip installation in A/B (Seamless) devices

@Yannik: It would be nice if you can help :)

**Comment by Yannik** [comment]
Can you give me a quick rundown of what you want to do? 
I could provide you with both an addon.d file and an updater-binary file for microg, because I built a microg zip myself. (it works on a/b + sys-as-root devices)

**Comment by ale5000-git** [comment]
First I don't have an a/b device.

I just want to be sure to do everything correctly to modify the system partition.
I have read that it have system_a and system_b, how can I know where to write?

**Comment by Yannik** [comment]
@ale5000-git In twrp the right /system is mounted automatically. 
Have a look at https://gitlab.com/fdroid/privileged-extension/blob/decd7f35ef64e8ec696d2a9feae38fd802479705/app/src/main/scripts/update-binary about system-as-root.
Also, look at this about the addon.d script:
https://gitlab.com/fdroid/privileged-extension/blob/d4a586304806903359312451a3e7eb2ac86fae3c/app/src/main/scripts/80-fdroid.sh

**Comment by Yannik** [comment]
I wrote a compatible addon.d script for microg:
```
#!/sbin/sh
#
# ADDOND_VERSION=2
#

. /tmp/backuptool.functions

PACKAGE_NAME=GmsCore

list_files() {
cat <<EOF
priv-app/${PACKAGE_NAME}.apk
priv-app/${PACKAGE_NAME}/${PACKAGE_NAME}.apk
EOF
}

case "$1" in
  backup)
    list_files | while read FILE DUMMY; do
      backup_file $S/"$FILE"
    done
  ;;
  restore)
    list_files | while read FILE REPLACEMENT; do
      R=""
      [ -n "$REPLACEMENT" ] && R="$S/$REPLACEMENT"
      [ -f "$C/$S/$FILE" ] && restore_file $S/"$FILE" "$R"
    done
  ;;
  pre-backup)
    # Stub
  ;;
  post-backup)
    # Stub
  ;;
  pre-restore)
    # Stub
  ;;
  post-restore)
    # Stub
  ;;
esac

```

Corresponding update-binary:```

# arg 1 is recovery api version, generally 3.
# arg 2 is the pipe fd, to the recovery binary.
# communicate with it using the recovery api.
# arg 3 is the zip file

PACKAGE_NAME=GmsCore

echo -n -e 'ui_print Installing GmsCore (MicroG) as a privileged app...\n' > /proc/self/fd/$2

APK_FILENAME=${PACKAGE_NAME}.apk
ADDOND=82-${PACKAGE_NAME}.sh
SYSTEM="/system"

mount_system() {
  mount /system

  # Modern devices use /system as root ("/")
  system_as_root=`getprop ro.build.system_root_image`
  if [ "$system_as_root" == "true" ]; then
    SYSTEM="/system/system"
  fi
}

cd /tmp
mkdir ${PACKAGE_NAME}
cd ${PACKAGE_NAME}
unzip -o "$3"

mount_system

rm -rf ${SYSTEM}/priv-app/${PACKAGE_NAME}*

PACKAGE_DIR="${SYSTEM}/priv-app/${PACKAGE_NAME}"
mkdir ${PACKAGE_DIR}
chmod 755 ${PACKAGE_DIR}

cp ${APK_FILENAME} ${PACKAGE_DIR}
chmod 644 ${PACKAGE_DIR}/${APK_FILENAME}

cp ${ADDOND} ${SYSTEM}/addon.d/

umount /system

echo -n -e 'ui_print done\n' > /proc/self/fd/$2
echo -n -e 'ui_print\n' > /proc/self/fd/$2

```

**Comment by ale5000-git** [comment]
I would like to know more the technical details if possible.

When someone flash a ROM, teorically it is flashed to the inactive partiton and then the active partition is changed by TWRP but if the OTA zip is only a mod and it is flashed without the ROM then the incative partition would contain only the files in the mod without the ROM and the partition switch would cause the device to not boot.
Or I'm wrong?

**Comment by Yannik** [comment]
Flashing a zip which is not a rom does not change the partition. Only flashing a ROM which rewrites /system causes a partition witch within twrp.

**Comment by ale5000-git** [comment]
So I think my OTA zip already works, thanks.

**Comment by ale5000-git** [comment]
Since it theoretically already works on A/B (Seamless) devices I will close the ticket.

If someone have any problem please open a new ticket.
