### ISSUE TITLE
Live setup failing

### ISSUE THREAD

**Issue by ZJaume** [micro5k/microg-unofficial-installer#5]
In TWRP 3.1.0 on samusng S7580 the 2 seconds delay to enable live setup are ignored. The message is displayed while flashing but the delay doesn't take place.

**Comment by ale5000-git** [comment]
@ZJaume
Could you please post the full log?
(do not copy it manually, but after flashing the zip use the option of the recovery to copy log ot sd and then post the file)

**Comment by ZJaume** [comment]
Log says "Illegal instruction". [https://pastebin.com/xMExzu4i](url)

**Comment by ale5000-git** [comment]
Hi,
could you please try this [one](https://www.androidfilehost.com/?fid=817906626617951914) and post the log?

**Comment by falcon4fun** [comment]
+
Installer don't wait for any input :) TWRP 2.8.7.2

**Comment by ale5000-git** [comment]
@ZJaume
@falcon4fun

Could both of you please try [this](https://www.androidfilehost.com/?w=files&flid=184629) and post here the log?

**Comment by ZJaume** [comment]
[https://pastebin.com/XRjAfwCa](url)

**Comment by ZJaume** [comment]
[https://pastebin.com/XRjAfwCa](url)

**Comment by ale5000-git** [comment]
@falcon4fun: Hi, I'm waiting also your log.

**Comment by falcon4fun** [comment]
@ale5000-git Here
https://pastebin.com/3pXgd0PM

**Comment by ale5000-git** [comment]
Unfortunately it seems that the problem isn't in my code but in keycheck binary.
Currently it cannot be fixed until I find a proper replacement for the keycheck binary.

**Comment by ale5000-git** [comment]
@ZJaume
@falcon4fun

It has taken some time but this is now fixed.
Could both of you please try this test build and report back?
https://androidfilehost.com/?fid=4279422670115712569

**Comment by falcon4fun** [comment]
> @ZJaume @falcon4fun
> 
> It has taken some time but this is now fixed. Could both of you please try this test build and report back? https://androidfilehost.com/?fid=4279422670115712569

Last time I used microG was around 3y ago :D

**Comment by ZJaume** [comment]
Sorry but I've been using LOS microg and LOS recvery since a couple years. Will tey to find if and old device and try it. Thanks!

**Comment by ale5000-git** [comment]
Don't worry if you no longer use it, in case you find it or start using it again I'm always here :-)
