### ISSUE TITLE
Google Play Store keeps trying to update GmsCore in the background

### ISSUE THREAD

**Issue by dalda123** [micro5k/microg-unofficial-installer#51]
I have clean flashed "microg-unofficial-installer-v1.2.0.5-alpha-by-ale5000-signed.zip" in recovery.
Everything intended is working fine.
But the Google Play Store is trying to update Google Play Services (which is MicroG GmsCore.apk) whenever I connect to the internet. It keeps trying to update in the background if I remain connected to the internet which is causing battery consumption when the device is idle.
This is because the version code of latest MicroG GsmCore.apk is lower than the latest original Google Play Services apk.
So my request is that please release a MicroG GmsCore.apk which has a greater version code than original Gms.
It would solve the problem of automatic update.
![Screenshot_20230124-171505_Launcher3](https://user-images.githubusercontent.com/37587853/214296718-f49d18c7-87d6-4945-b508-441afc9b782c.png)
![-6231117963419825006_121](https://user-images.githubusercontent.com/37587853/214296758-f76bed56-b586-4d35-af11-5d549a553b17.jpg)

**Comment by ale5000-git** [comment]
This isn't related to the installer, anyway it got updated here: https://github.com/microg/GmsCore/commit/ee3c269ac3b91fda06250f41b4486c497489cfb7
So it will be in the next version.
