### ISSUE TITLE
Sideloading results in indefititely long fallback "waiting input"

### ISSUE THREAD

**Issue by amo13** [micro5k/microg-unofficial-installer#59]
First things first, thank you a lot for creating and maintaining this microG installer. I just started integrating it into my [Rom installation assistant](https://github.com/amo13/Anarchy-Droid) because the latest builds of [NanoDroid](https://gitlab.com/Nanolx/NanoDroid) seem to be outdated and the maintenance a little scarce.

My application needs to sideload everything so that the user does not need to intervene. After sideloading the current version of your microG installer (on osprey), I see the message on the phone screen:
```
------------------------
INFO: Select the VOLUME + key to enable live sertup.
-------------------------
Waiting input for 2 seconds...

WARNING: timeout returned cmd NOT found (127)
Fallbacking to manual input parsing, waiting input...
```
At this point, the installation hangs indefinitely. At least it has stayed like that for almost an hour now. 
Is there a way to tell the installation script that interactivity is not desired? 

I have seen in your code that sideload should be detected but there is no output on the screen telling that is has been detected.

**Comment by ale5000-git** [comment]
Hi,
currently the "fallback to manual input parsing" doesn't have a timeout, it will be fixed in a new version.
The sideload message is displayed later in the process, but it is only done to change the path of the debug log.

To disable the wait completely you can set LIVE_SETUP_TIMEOUT to 0.
In the repository the settings are in these files (it depends if it is the OSS version or the full version):
https://github.com/micro5k/microg-unofficial-installer/blob/main/zip-content/settings-full.conf
https://github.com/micro5k/microg-unofficial-installer/blob/main/zip-content/settings-oss.conf

**Comment by amo13** [comment]
Thank you for your answer.
Do you think there is a way to set the configuration dynamically? Like with an environment variable or some TWRP variable?
Otherwise, would I need to "build" the flashable zip with modified settings by myself? How would I create such a build or release as flashable zip?

**Comment by ale5000-git** [comment]
1) The only way that I know to set the configuration dynamically is to run from an adb shell:
- Send the zip to the device
- Send zip-install.sh to the device: https://github.com/micro5k/microg-unofficial-installer/blob/main/zip-content/zip-install.sh
- Then open adb shell
- The run: CI=true sh ./zip-install.sh ./zip-name.zip
With CI=true it will skip all dynamic questions.

2) If it were executed from a normal shell yes, but with sideload I don't think environment variables will be kept.

3)I don't know about TWRP variables, do you have any link for this?

4) To build you can set:
`export OPENSOURCE_ONLY='true'`
or
`export OPENSOURCE_ONLY='false'`

and then on Windows:
`build.bat`
or on other OSes:
`./build.sh`

Alternatively you can use gradle as explained here: https://github.com/micro5k/microg-unofficial-installer/blob/main/docs/INSTRUCTIONS.rst

**Comment by amo13** [comment]
Amazing! Thank you a lot for the instructions and detailed ideas!
Looking forward to the next release including a timeout for the manual input.
Any chance you can publish the full version as an additional asset in the github releases? Programmatically scraping the xda forum for the link to the latest "full" release is sort of a pain.

**Comment by ale5000-git** [comment]
It isn't included here to prevent any possible problem, but the link is always the same: https://androidfilehost.com/?w=files&flid=141201
(once there is a new version, then the old one is moved to the Archive subfolder.

**Comment by ale5000-git** [comment]
@amo13
I have got an idea that may work, using getprop and setprop some settings can be configured (these settings will survive only until a reboot).
I will implement it when I have time.

**Comment by amo13** [comment]
> I have got an idea that may work, using getprop and setprop some settings can be configured (these settings will survive only until a reboot). I will implement it when I have time.

That sounds like a great idea! 

And thanks for the permalink to androidfilehost. I'll try to use thatonce they resolve their `Fatal error: Uncaught Error: Call to a member function execute() on null in /web/libs/classes/SqlCache.php:16` :laughing:

**Comment by amo13** [comment]
Can't download programmatically from androidfilehost. They have an api but you need a key for direct download of files and only developers with beta access get one right now... I will host the full version and the google sync adapters on my server and will let my application download them from there.

**Comment by ale5000-git** [comment]
I have written the code to set LIVE_SETUP_TIMEOUT, but the nwe version of the zip isn't ready yet.

When it is released you will be able to set it with:
`adb shell "setprop zip.microg-unofficial-installer.LIVE_SETUP_TIMEOUT 0"`

**Comment by amo13** [comment]
Amazing! This solution is so much more elegant than sending a configuration file, which I needed to do for nanodroid.

Is it possible to configure INSTALL_FDROIDPRIVEXT and INSTALL_NEWPIPE the same way? For example for skipping newpipe installation.

**Comment by ale5000-git** [comment]
Now it should work with all settings:
```
adb shell "setprop zip.microg-unofficial-installer.LIVE_SETUP_DEFAULT 0"
adb shell "setprop zip.microg-unofficial-installer.LIVE_SETUP_TIMEOUT 0"
```

```
adb shell "setprop zip.microg-unofficial-installer.INSTALL_FDROIDPRIVEXT 1"
adb shell "setprop zip.microg-unofficial-installer.INSTALL_NEWPIPE 1"
adb shell "setprop zip.microg-unofficial-installer.INSTALL_PLAYSTORE 1"
adb shell "setprop zip.microg-unofficial-installer.INSTALL_ANDROIDAUTO 1"
```

**Comment by amo13** [comment]
Wow, this is awesome!
Great work, thank you!

**Comment by ale5000-git** [comment]
@amo13

Some infos for better error handling:
getprop works only as root; TWRP that I know already start as root but who knows.

To be more sure you can run:
`adb shell "whoami"`
and then check that the result is `root`

adb shell does NOT properly forward the return value on old ROM (maybe also on old recoveries) so you can check that the command is working with:
`adb shell "setprop zip.microg-unofficial-installer.INSTALL_PLAYSTORE 1 2> /dev/null && echo OK || echo ERROR"`
and then checkig the outout.

**Comment by ale5000-git** [comment]
Everything is fixed now, it will be ported to the Google Sync add-on soon as well.

**Comment by ale5000-git** [comment]
Now there is also:
`adb shell "setprop zip.microg-unofficial-installer.INSTALL_AURORASERVICES 1"`

**Comment by amo13** [comment]
Wow, this is awesome!
Great work, thank you!

**Comment by ale5000-git** [comment]
Hi,
I have released a new version of microG unofficial installer.

Looking at [your code](https://github.com/amo13/Anarchy-Droid/commit/0b8f8758e0ad17431c6b170998015bdbd32d2ff9#diff-5e629170ab387324849d29388a8f50193cc5653f20c32a40fc6dcacf855a2babR800) the full version is downloaded `if Chk_gsync.Checked || Chk_playstore.Checked` but the full version contains in addition just Play Store and Android Auto so it isn't related to sync that is a separate add-on.

**Comment by ale5000-git** [comment]
@amo13
Hi,
I have released a new version of microG unofficial installer.

Looking at [your code](https://github.com/amo13/Anarchy-Droid/commit/0b8f8758e0ad17431c6b170998015bdbd32d2ff9#diff-5e629170ab387324849d29388a8f50193cc5653f20c32a40fc6dcacf855a2babR800) the full version is downloaded `if Chk_gsync.Checked || Chk_playstore.Checked` but the full version contains in addition just Play Store and Android Auto so it isn't related to sync that is a separate add-on.

**Comment by amo13** [comment]
You are right. I appreciate the review!

**Comment by ale5000-git** [comment]
There is another issue that I noticed now but it is just minor, here:
https://github.com/amo13/Anarchy-Droid/blob/90cbe9d6482508fd8210e35df03cb53c2117b5b6/settingstab.go#L457
it seems to open the MinMicroG page for my installer.

If you need a page that show the content, then it is here: https://github.com/micro5k/microg-unofficial-installer/blob/main/zip-content/CONTENTS.rst

**Comment by amo13** [comment]
Thank you, fixed it. It's going to be published in the next release.
