### ISSUE TITLE
Imei number

### ISSUE THREAD

**Issue by ankit125664** [micro5k/microg-unofficial-installer#68]
Script unable to find the imei number in the android 13

**Comment by ale5000-git** [comment]
Hi,
I guess you are talking about this script: https://github.com/micro5k/microg-unofficial-installer/blob/main/utils/device-info.sh

Could you please explain in more detail?
Does it give an error message?
What is it displayed exactly?

**Comment by ale5000-git** [comment]
@ankit125664
Since it works for me, I need more detail to discover the problem.

**Comment by ale5000-git** [comment]
It works perfectly for me, without any additional info there is no way to know what is the problem.
