### ISSUE TITLE
Using Fdroid apk builds so that they can be updated through any fdroid client 

### ISSUE THREAD

**Issue by ghazzor** [micro5k/microg-unofficial-installer#83]
### Checklist

- [X] I have updated your software to the **latest version** and I have verified that the requested feature is **NOT** already in it.
- [X] I made sure that there weren't already **[feature requests](../labels/enhancement)** for the same feature.

### Feature description

as stated in title

**Comment by ale5000-git** [comment]
Can you please explain in details?
By default the microG Services that it is installed is the official version; it only install my custom version if you enable the option `USE_GMSCORE_BY_ALE5000` (`USE_MICROG_BY_ALE5000` in the next versions) before flashing the zip.

**Comment by ghazzor** [comment]
> Can you please explain in details? By default the microG Services that it is installed is the official version (that can be updated through F-Droid); it only install my custom version if you enable the option `USE_GMSCORE_BY_ALE5000` (`USE_MICROG_BY_ALE5000` in the next versions) before flashing the zip.

i tried updating through fdroid but it failed (signature mismatch) but it updated if i downloaded apk from official microg website

**Comment by ale5000-git** [comment]
Sometimes there may be issues with the microG repository or with F-Droid itself.
The fact that microG use signature spoofing add additional complications because F-Droid isn't able the see the real signature; the microG repository has a workaround for this issue but problems may arise.

**Comment by ghazzor** [comment]
> Sometimes there may be issues with the microG repository or with F-Droid itself. The fact that microG use signature spoofing add additional complications because F-Droid isn't able the see the real signature; the microG repository has a workaround for this issue but problems may arise.

hmm , so no fix for this ?

**Comment by ale5000-git** [comment]
The microG installed by default is the one with official signature.
Other than this I cannot do anything.
This problem annoy also me but I haven't found any solution.

You could try to find where this problem is reported in F-Droid support and write there.
If they don't find a way to overcome the problem of signature spoofing then I think that there isn't any alternative.
