### ISSUE TITLE
device-info.sh results in error "-bash: @: unbound variable"

### ISSUE THREAD

**Issue by jpage4500** [micro5k/microg-unofficial-installer#84]
### What happened?

Hi,

I found this script in a stackoverflow post and was hoping it'd print my device IMEI. I tried running it though and just get the error below:

```
Android device info extractor v1.5 by ale5000
-bash: @: unbound variable

```

I'm on a M1 Mac and my devices is a Pixel 7, Android 14

I'll try to debug but wanted to mention it in case there's some easy fix

### Version

1.5

### Android version

14

### Custom ROM

Google

**Comment by ale5000-git** [comment]
@jpage4500
Hi,
it is an incompatibility of bash under Mac compared to bash under all other OSes.
I have found a workaround to have it working, could you please try the new version?

**Comment by jpage4500** [comment]
@ale5000-git - that worked - thanks for the quick response!!

**Comment by jpage4500** [comment]
Hi @ale5000-git -- this issue is closed but I wanted to mention 1 thing and ask a follow-up question if you don't mind

1) I have multiple devices connected to my laptop and wanted to use this script to print out details for all of them; I was able to modify the script to do this. Not sure if you're interested in that change or not but the gist of my changes was to add this:
```
DEVICES=$(adb devices -l | grep -v "List" | grep -v "offline" | grep -v '^$' | sed 's/ device:.*//' | cut -d ' ' -f 1 | tr '\n' ' ')
for device in $DEVICES
do
    export ADB_DEVICE=$(echo "$device" | sed $'s/[ \t].*$//g')
    main
done
```

Then, of course, every time there's an adb command like `adb shell`, I replaced it with `adb -s $ADB_DEVICE shell`

I did have to make a couple of other minor changes like not making BUILD_VERSION_SDK readonly.. also, the wait for device check failed because there was multiple devices connected.. but, essentially that was it and now it's printing out info for every connected device!
```
  #readonly BUILD_VERSION_SDK
```

2) I have several test devices that don't log the phone number and I can't figure out why.. the confusing part is I have the other devices - same device/OS/SIM/etc which show the phone number fine.

The devices in question are Samsung A21, model: SM-G991U1, OS:14
![image](https://github.com/micro5k/microg-unofficial-installer/assets/1895553/e13fde28-98d4-4b45-b530-09c1f3df8f5f)

**Comment by ale5000-git** [comment]
@jpage4500
I have intention to add support for multiple devices.
But I want to do it in a way that it also allow to select device so I need some time to do it properly.

PS: Please open a separate ticket for bugs like phone number not extracted correctly.

**Comment by ale5000-git** [comment]
@jpage4500
I have added support for multiple devices in the script but it isn't yet perfect.

**PS:** Please open a separate ticket for bugs like phone number not extracted correctly.
